version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kgs_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kgs
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kgs"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: kgs_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # Именно это прочитает твой prisma.config.ts внутри контейнера
      # ! EXAMPLE: DATABASE_URL: "postgresql://user:1234@db:5432/dbName?schema=public"
      DATABASE_URL: ""
    depends_on:
      db:
        condition: service_healthy