// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "path";
import { defineConfig } from "prisma/config";
import { config } from "dotenv";

const envFile = process.env.NODE_ENV === 'production' ? '.env.prod' : '.env.local';

config({ path: path.resolve(process.cwd(), envFile) });

console.log(`Loading config from: ${envFile}`);
console.log("DB URL Check:", process.env.DATABASE_URL);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
